# Server Port
server:
  port: 8001

# Callback Url to Authen Service
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8000/api/v1/auth/user

# Register Eureka Service
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

